name: Release

on:
  push:
    branches: [ "master" ]
    paths:
    - "data/**"
  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          yarn install
          yarn build
          gh release create $(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1) public/*
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image and push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          IMAGE_VERSION=`cat package.json | jq -r '.version'`
